<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <WasmFingerprintDotnetJs>false</WasmFingerprintDotnetJs>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishTrimmed>true</PublishTrimmed>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot/lib/**;wwwroot/sample-data/**;wwwroot/favicon.png;wwwroot/icon-192.png" />
    <ProjectReference Include="../../src/Ludo.Presentation/Ludo.Presentation.csproj" />
    <Content Include="../../assets/ludo/*.png" Link="wwwroot/assets/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />
  </ItemGroup>

</Project>
